### ISSUE TITLE
getPayload has insufficient checks, allows validator to access the block contents without slashing

### ISSUE THREAD

**Issue by metachris** [blocknative/dreamboat#6]
The getPayload checks in https://github.com/blocknative/dreamboat/blob/main/pkg/api.go#L172 / https://github.com/blocknative/dreamboat/blob/main/pkg/relay.go#L312 are insufficient, and allow a validator to steal the payload without risk of slashing. besides checking the blockhash, also the correct slot and proposer index need to be verified.

See the mev-boost audit for more details: https://github.com/flashbots/mev-boost/blob/main/docs/audit-20220620.md#relayer-signedblindedbeaconblock-validation

> Relayer SignedBlindedBeaconBlock validation
>
> To be slashed, a validator would need to sign two competing blocks for the block of the slot they are in charge of producing.
>
> As such, relayers need to validate the SignedBlindedBeaconBlock signed by validators to be of the correct Slot and ProposerIndex before showing the unblinded block to the validator. If this is not checked, validators will be able to access the block contents and use these transactions to craft a new block, where they extract the MEV for themselves.

**Comment by aratz-lasa** [comment]
Thank you very much for opening this issue @metachris . I just opened a PR to fix this issue!

**Comment by lthibault** [comment]
Fixed by #7 

@metachris Thanks for the assist -- much appreciated! 🤝
